apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgsql-deployment
spec:
  selector:
    matchLabels:
      app: pgsql
  replicas: 1
  template:
    metadata:
      name: pgsql-replicaset
      labels:
        app: pgsql
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/verdant-descent-421106/vote-image/pgsql
        name: pgsql-pod
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            subPath: data
            name: db-data
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-pvc 