apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: db
  labels:
    kubernetes.io/service-name: db
addressType: IPv4
ports:
  - port: 5432
endpoints:
  - addresses:
    - 35.226.168.43