apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  selector:
    matchLabels:
      app: result
  replicas: 1
  template:
    metadata:
      name: result
      labels:
        app: result
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/verdant-descent-421106/vote-image/result
        name: result