apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
spec:
  selector:
    matchLabels:
      app: vote
  replicas: 5
  template:
    metadata:
      name: vote-replicaset
      labels:
        app: vote
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/verdant-descent-421106/vote-image/vote
        name: vote-pod
        livenessProbe:
          httpGet:
            path: /
            port: 5000