apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      name: worker
      labels:
        app: worker
    spec:
      containers:
      - image: europe-west9-docker.pkg.dev/verdant-descent-421106/vote-image/worker
        name: worker