all:
  hosts:
    PrimaryVM:
      ansible_host: 35.226.168.43
      ansible_user: Cub
      ansible_port: 22
      ansible_ssh_private_key_file: "~/.ssh/google_compute_engine"
    StandbyVM:
      ansible_host: 34.133.215.188
      ansible_user: Cub
      ansible_port: 22
      ansible_ssh_private_key_file: "~/.ssh/google_compute_engine"